{% set version="0.6.4" %}

package:
  name: usher
  version: {{ version }}

source:
  - url: https://github.com/yatisht/usher/archive/v{{ version  }}.tar.gz
    sha256: f9c38f7bf65ec22f22620917ec3c4c99fc23e96cbd75c03f104a8b03533674fd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('usher', max_pin="x.x") }}

requirements:
  build:
    - make
    - autoconf
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - wget
  host:
    - boost-cpp
    - libprotobuf
    - openmpi =4.1.2
    - openssh
    - isa-l
  run:
    - mafft
    - boost-cpp
    - ucsc-fatovcf
    - openmpi =4.1.2
    - openssh
    - isa-l

test:
  commands:
    - usher --help
    - usher-sampled --help
    - matOptimize --help
    - matUtils --help

about:
  home: https://github.com/yatisht/usher
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ultrafast Sample Placement on Existing Trees (UShER)
  doc_url: https://usher-wiki.readthedocs.io/en/latest/

extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - doi:10.1038/s41588-021-00862-7
