{% set name = "perl-image-exiftool" %}
{% set version = "13.00" %}
{% set sha256 = "4895788f34f834765f86be4a5ad5a32433f572d757160ecd7b612eaf5ed37e84" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-13.00.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  
requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Image::ExifTool
  commands:
    - exiftool -ver

about:
  home: https://metacpan.org/pod/Image::ExifTool
  license: perl_5
  summary: 'ExifTool is a platform-independent Perl library plus a command-line application for reading, writing and editing meta information in a wide variety of files.'
