{% set name = "ms2rescore-rs" %}
{% set version = "0.2.1" %}
{% set sha256 = "574b65ac20000ef1a5acc2332174e9fc7fbacc36bc314eedfea8ed8d9220c51d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ms2rescore_rs-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py < 38]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - make
    - cmake
  host:
    - zlib
    - python
    - maturin >=1.5,<2.0
    - pip
  run:
    - python

test:
  imports:
    - ms2rescore_rs

about:
  home: https://github.com/compomics/ms2rescore-rs
  summary: "Rust functionality for the MS²Rescore package"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CompOmics
    - RalfG
