{% set name = "lib-pod5" %}
{% set version = "0.3.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nanoporetech/pod5-file-format/releases/download/{{ version }}/pod5-{{ version }}.tar.gz
  sha256: ff1010dfd2a0ee26d1ee539a9b9a86c03d152e1c8652317f772c0d29c122b3ab

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install https://files.pythonhosted.org/packages/ab/6a/82e5b695e5bc7c3f74df911cd07b80948403425e866a48bfd8e56d610673/lib_pod5-{{ version }}-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl -vvv --no-deps --no-build-isolation --no-cache-dir  # [linux and x86_64]
    - {{ PYTHON }} -m pip install https://files.pythonhosted.org/packages/4b/e1/ca79a961f0d0b1898bde038152c8fd0fa75db8e419a77cf2a7315850f075/lib_pod5-{{ version }}-cp313-cp313-manylinux_2_17_aarch64.manylinux2014_aarch64.whl -vvv --no-deps --no-build-isolation --no-cache-dir  # [linux and aarch64]
    - {{ PYTHON }} -m pip install https://files.pythonhosted.org/packages/c8/ea/106fb9e760b9e7ca5c4809e8c5436851b1593a4e40fd42d05f45e2a03aec/lib_pod5-{{ version }}-cp313-cp313-macosx_10_15_universal2.whl -vvv --no-deps --no-build-isolation --no-cache-dir  # [osx and x86_64]
    - {{ PYTHON }} -m pip install https://files.pythonhosted.org/packages/e8/1a/be90eeef6a976a77c35752c5be56f786ac590ad8817e8daadac5dbf6a2c8/lib_pod5-{{ version }}-cp313-cp313-macosx_11_0_arm64.whl -vvv --no-deps --no-build-isolation --no-cache-dir  # [osx and arm64]
  run_exports:
    - {{ pin_subpackage('lib-pod5', max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - pybind11 >=2.10.0
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=1.21.0

test:
  imports:
    - lib_pod5

about:
  home: https://github.com/nanoporetech/pod5-file-format
  summary: "Python bindings for the POD5 file format."
  license: "MPL-2.0"
  license_family: OTHER
  license_file: "LICENSE.md"
  dev_url: https://github.com/nanoporetech/pod5-file-format
  doc_url: https://pod5-file-format.readthedocs.io/en/latest
  description: |
    [![Documentation Status](https://readthedocs.org/projects/pod5-file-format/badge/?version=latest)](https://pod5-file-format.readthedocs.io/)

    **Python bindings for the POD5 file format**

    What does this project contain
    ------------------------------

    This project contains the low-level core library (extension modules) for reading and writing POD5 files.
    This project forms the basis of the pure-python [pod5 package](https://github.com/nanoporetech/pod5-file-format) which is probably the project you want.

    Documentation
    -------------

    Full documentation is found at https://pod5-file-format.readthedocs.io
