{% set version = "0.13.1" %}

package:
  name: varfish-server-worker
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]
  run_exports:
    - {{ pin_subpackage("varfish-server-worker", max_pin="x.x") }}

source:
  url: https://github.com/varfish-org/varfish-server-worker/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 88fb4c61f32a43b17e9cbe7bdb756485c9802b5cbb53bdb5884a28a075b06a86

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - clangdev
    - pkg-config
    - protobuf
    - make
    - cmake
  host:
    - clangdev
    - openssl
    - sqlite
    - zlib
  run:
    - sqlite

test:
  commands:
    - varfish-server-worker --help

about:
  home: https://github.com/varfish-org/varfish-server-worker
  license: MIT
  summary: |
    Rust-based tool for the heavy lifting in varfish-server.

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - holtgrewe
