{% set version = "0.16.1" %}

package:
  name: varfish-server-worker
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]
  run_exports:
    - {{ pin_subpackage("varfish-server-worker", max_pin="x.x") }}

source:
  url: https://github.com/varfish-org/varfish-server-worker/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ef1ee2421a260b21a058af8adfb31f8cdf606bf110c7e31c980101b7cc7c2ff9

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - pkg-config
    - make
    - cmake
  host:
    - clangdev
    - openssl
    - sqlite
    - zlib
    - clangdev
    - protobuf
  run:
    - sqlite

test:
  commands:
    - varfish-server-worker --help

about:
  home: https://github.com/varfish-org/varfish-server-worker
  license: MIT
  license_family: MIT
  summary: |
    "Rust-based tool for the heavy lifting in varfish-server."
  dev_url: https://github.com/varfish-org/varfish-server-worker

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - holtgrewe
