{% set name = "perl-getopt-long-descriptive" %}
{% set version = "0.115" %}
{% set sha256 = "ea1185a9465cf0790e81827f13c860f18e40ab817ad03b9659a9f28ae1ec5411" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-0.115.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - make
  host:
    - perl
    - perl-test-warnings >=0.005
    - perl-cpan-meta-check
    - perl-carp
    - perl-cpan-meta-requirements
    - perl-sub-exporter
    - perl-params-validate
    - perl-extutils-makemaker
    - perl-test-fatal
    - perl-getopt-long

  run:
    - perl
    - perl-carp
    - perl-getopt-long
    - perl-sub-exporter
    - perl-params-validate

test:
  imports:
    - Getopt::Long::Descriptive
    - Getopt::Long::Descriptive::Opts
    - Getopt::Long::Descriptive::Usage

about:
  home: https://github.com/rjbs/Getopt-Long-Descriptive
  license: perl_5
  summary: 'Getopt::Long, but simpler and more powerful'
