{% set version = "2.3.0" %}
{% set sha256 = "e3d15d065148ed9dd25315868a31ec6c8a645d254a28ff2dcd01b23aed8b136d" %}

package:
  name: palikiss
  version: 1.1.0

source:
  sha256: {{ sha256 }}
  # the repository "fold-grammars" contains sources for several programs, i.e. pKiss, RNAshapes, ...
  # thus, the version number does not correspond to the pAliKiss version number
  url: https://github.com/jlab/fold-grammars/archive/{{ version }}.tar.gz

build:
  number: 0
  skip: False # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas
  run:
    - {{ compiler('cxx') }}
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas

test:
  commands:
    - pAliKiss -h
    - pAliKiss CGCAUGCUAGUCGCG

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/palikiss
  license: 'GPLv3+'
  license_file: LICENSE
  summary: "pAliKiss predicts RNA secondary structures for fixed RNA multiple sequence alignments, with special attention for pseudoknotted structures."

extra:
  identifiers:
    - doi:10.1007/978-3-642-15294-8_5
    - doi:10.1093/bioinformatics/btu649
