{% set version = "0.42.3" %}

package:
  name: annonars
  version: {{ version }}

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("annonars", max_pin="x.x") }}

source:
  url: https://github.com/varfish-org/annonars/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0dc452beb8d5c1810bd0e4309b918e2830cb034b6993492392206a7da269e1dd

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - pkg-config
    - make
    - cmake
    - libprotobuf
    - rocksdb
    - snappy
  host:
    - clangdev
    - libprotobuf
    - openssl
    - rocksdb
    - sqlite
    - zlib
  run:
    - rocksdb
    - sqlite

test:
  commands:
    - annonars --help

about:
  home: https://github.com/varfish-org/annonars
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'Genome annotation based on Rust and RocksDB.'
  dev_url: https://github.com/varfish-org/annonars

extra:
  recipe-maintainers:
    - holtgrewe
    - tedil
#  additional-platforms:
#    - linux-aarch64
