{% set version = "0.41.2" %}

package:
  name: annonars
  version: {{ version }}

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("annonars", max_pin="x.x") }}

source:
  url: https://github.com/varfish-org/annonars/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e0c666204fcea6e559a704220959c1d2608ae11d00282201bb5bcf4760e5d59a

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - pkg-config
    - make
    - cmake
  host:
    - clangdev
    - libprotobuf
    - openssl
    - sqlite
    - zlib
  run:
    - sqlite

test:
  commands:
    - annonars --help

about:
  home: https://github.com/varfish-org/annonars
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'Genome annotation based on Rust and RocksDB.'
  dev_url: https://github.com/varfish-org/annonars

extra:
  recipe-maintainers:
    - holtgrewe
    - tedil
  additional-platforms:
    - linux-aarch64
