{% set version = "0.41.1" %}

package:
  name: annonars
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]
  run_exports:
    - {{ pin_subpackage("annonars", max_pin="x.x") }}

source:
  url: https://github.com/varfish-org/annonars/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2c9289df260c1eed9ac805d1b468d380ae706b1cd25fb568313ba3811f3da8b4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust >=1.30
    - clangdev
    - pkg-config
    - protobuf
    - make
    - cmake
  host:
    - clangdev
    - openssl
    - sqlite
    - zlib
  run:
    - sqlite

test:
  commands:
    - annonars --help

about:
  home: https://github.com/varfish-org/annonars
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Genome annotation based on Rust and RocksDB.'

extra:
  recipe-maintainers:
    - holtgrewe
    - tedil
  additional-platforms:
    - linux-aarch64
