{% set version = "2.3.0" %}
{% set packagename = "rapidshapes" %}
{% set sha256 = "e3d15d065148ed9dd25315868a31ec6c8a645d254a28ff2dcd01b23aed8b136d" %}

package:
  name: {{ packagename }}
  version: 2.1.0

source:
  sha256: {{ sha256 }}
  # the repository "fold-grammars" contains sources for several programs, i.e. pKiss, RNAshapes, ...
  # thus, the version number does not correspond to the {{ packagename }} version number
  url: https://github.com/jlab/fold-grammars/archive/{{ version }}.tar.gz

build:
  number: 0
  skip: False # [osx]
  run_exports:
    - {{ pin_subpackage('{{ packagename }}', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas
  run:
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas

test:
  commands:
    - RapidShapes -h
    - RapidShapes CGCAUGCUAGUCGCG

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/{{ packagename }}
  license: 'GPLv3+'
  license_file: LICENSE
  summary: "RapidShapes computes a thermodynamic matcher (TDM), using a runtime heuristic for probabilistic shape analysis."

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btu649
