{% set package = "ucsc-bedtobigbed" %}
{% set program = "bedToBigBed" %}
{% set version = "467" %}
{% set sha256 = "0d1770b2492642d8c1af9e42c1426ff50586421b6f1404804956b57541ee295f" %}

package:
  name: {{ package }}
  version: {{ version }}

source:
  url: "https://hgdownload.cse.ucsc.edu/admin/exe/userApps.archive/userApps.v{{ version }}.src.tgz"
  sha256: {{ sha256 }}
  patches:
    - include.patch
    - htmshell.patch

build:
  number: 0
  skip: True # [osx]
  ignore_run_exports:
    - libpng
    - libuuid
  run_exports:
    - {{ pin_subpackage(package, max_pin=None) }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils # [linux]
  host:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl
    - libopenssl-static
    - zlib
  run:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl

test:
  commands:
    # just check for existence, because the individual packages have no unified behavior
    - which {{ program }}

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  summary: "Convert bed file to bigBed. (bbi version: 4)"

extra:
  additional-platforms:
    - linux-aarch64