{% set package = "ucsc-bedtobigbed" %}
{% set program = "bedToBigBed" %}
{% set version = "467" %}

package:
  name: {{ package }}
  version: {{ version }}

source:
  url: "https://github.com/ucscGenomeBrowser/kent/archive/refs/tags/v{{ version }}_base.tar.gz"
  sha256: "27a139d71354645fd8366c82e7028a0b62212af0af4b2a407c1b000e28bbb4fd"

build:
  number: 0
  skip: True # [osx]
  ignore_run_exports:
    - libpng
    - libuuid
  run_exports:
    - {{ pin_subpackage(package, max_pin=None) }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils # [linux]
  host:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl
    - libopenssl-static
    - zlib
  run:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl

test:
  commands:
    # just check for existence, because the individual packages have no unified behavior
    - which {{ program }}

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  summary: "Convert bed file to bigBed. (bbi version: 4)"

extra:
  additional-platforms:
    - linux-aarch64