{% set version = "0.29.0" %}
{% set sha256 = "7b4d233bcce0946a4f42e3c8a422062bfadc63dee5bce3927763f7b90b1dd70d" %}

package:
  name: mehari
  version: {{ version }}

source:
  url: https://github.com/varfish-org/mehari/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-release-profile.patch

build:
  skip: True  # [osx]
  number: 0
  run_exports:
    - {{ pin_subpackage("mehari", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - pkg-config
    - libprotobuf
    - rocksdb
    - snappy
  host:
    - clangdev
    - openssl
    - protobuf
    - sqlite
    - zlib
  run:
    - sqlite

test:
  commands:
    - mehari -h

about:
  home: https://github.com/varfish-org/mehari
  license: MIT
  license_family: MIT
  summary: VEP-like tool for sequence ontology and HGVS annotation of VCF files written in Rust.
  dev_url: https://github.com/varfish-org/mehari

## Currently, there is no rocksdb package available from conda for linux-aarch64, skip for now.
#extra:
#  additional-platforms:
#    - linux-aarch64
