{% set version = "2.3.0" %}
{% set sha256 = "e3d15d065148ed9dd25315868a31ec6c8a645d254a28ff2dcd01b23aed8b136d" %}

package:
  name: acms
  version: 1.3.0

source:
  sha256: {{ sha256 }}
  # the repository "fold-grammars" contains sources for several programs, i.e. pKiss, RNAshapes, ...
  # thus, the version number does not correspond to the RNAshapes version number
  url: https://github.com/jlab/fold-grammars/archive/{{ version }}.tar.gz

build:
  number: 0
  skip: False # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas
  run:
    - {{ compiler('cxx') }}
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas

test:
  commands:
    - aCMs -h

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/acms
  license: 'GPLv3+'
  license_file: LICENSE
  summary: " Covariance models (CMs), as defined by Sean Eddy, do not reward insertions of valid base-pairs or complete sub-structures relative to the one consensus secondary structure. Nevertheless, some families, e. g. tRNA, contain minorities with additional informative sub-structures, which are crashed by the majority during formation of one consensus secondary structure.

Ambivalent Covariance Models (aCMs) are our prototypic suggestion to extend CMs with more than one consensus structure."

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btu649
