{% set name = "btllib" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcgsc/btllib/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 8c046340b9db4d580521297bfd9cb55af6877a34b48cf6a053266703ebc17837

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('btllib', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - meson
    - ninja
  host:
    - python
    - pip
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - samtools
    - swig
    - doxygen
  run:
    - python
    - samtools
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pigz
    - gzip  # alternative to pigz
    - tar
    - bzip2
    - xz
    - lrzip # [not arm64]
    - zip
    - wget

test:
  commands:
    - indexlr --help
  imports:
    - btllib

about:
  home: https://github.com/bcgsc/btllib
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'Bioinformatics common code library in C++ with Python wrappers, from Bioinformatics Technology Lab'
  doc_url: https://bcgsc.github.io/btllib/
  dev_url: https://github.com/bcgsc/btllib

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.21105/joss.04720
    - doi:10.1093/bioadv/vbad162
