c_stdlib_version:              # [unix]
  - 2.17                       # [linux and x86_64]
  - 2.17                       # [linux and not x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - "10.13"                    # [osx]
MACOSX_SDK_VERSION:            # [osx]
  - "10.13"                    # [osx]
