{% set name = "vcflib" %}
{% set version = "1.0.12" %}
{% set sha256 = "cb1e78d675f06ae3b22ffed7e1dea317e4c7f826e51e5b5dabd80240efbe1019" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
- url: https://github.com/vcflib/vcflib/releases/download/v{{ version }}/{{ name }}-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-CMakeLists.patch
    - tabix.patch
- url: https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz  # [linux and x86_64]
  sha256: 2d00e789fec4f71790a6e7bf83ff91d564943c5ee843c5fd966efc474b423047  # [linux and x86_64]
  folder: zig-linux-x86_64-0.11.0  # [linux and x86_64]
- url: https://ziglang.org/download/0.11.0/zig-linux-aarch64-0.11.0.tar.xz  # [linux and aarch64]
  sha256: 956eb095d8ba44ac6ebd27f7c9956e47d92937c103bf754745d0a39cdaa5d4c6  # [linux and aarch64]
  folder: zig-linux-aarch64-0.11.0  # [linux and aarch64]
- url: https://ziglang.org/download/0.11.0/zig-macos-x86_64-0.11.0.tar.xz  # [osx and x86_64]
  sha256: 1c1c6b9a906b42baae73656e24e108fd8444bb50b6e8fd03e9e7a3f8b5f05686  # [osx and x86_64]
  folder: zig-macos-x86_64-0.11.0  # [osx and x86_64]
- url: https://ziglang.org/download/0.11.0/zig-macos-aarch64-0.11.0.tar.xz  # [osx and arm64]
  sha256: c6ebf927bb13a707d74267474a9f553274e64906fd21bf1c75a20bde8cadf7b2  # [osx and arm64]
  folder: zig-macos-aarch64-0.11.0  # [osx and arm64]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('vcflib', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
    - pybind11-global
    # python really only used as a build tool; no ${PREFIX}/bin/python needed.
    - python >=3
    - pkg-config
  host:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - zlib
    - htslib
    - tabixpp
    - wfa2-lib
    - pandoc
  run:
    - python >=3
    - perl
    - htslib
    - tabixpp
    - wfa2-lib
    - eigen
    - jsoncpp
    - wget

test:
  requires:
    - wget
  commands:
    - "vcfwave -h"
    - "vcffirstheader < /dev/null"
    - "vcfsort < /dev/null"
    - "vcfstreamsort --help"
    - "wget -O test.vcf https://raw.githubusercontent.com/vcflib/vcflib/a610b7444daab0c9e974d9a001550bf8dd644770/test/data/regression/vcffilter_2.vcf"
    - "vcfuniq test.vcf"

about:
  home: "https://github.com/vcflib/vcflib"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Command-line tools for manipulating VCF files."
  dev_url: "https://github.com/vcflib/vcflib"
  doc_url: "https://github.com/vcflib/vcflib/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    #zig osx-arm64 error: error(link): undefined reference to symbol 'dyld_stub_binder'
    - osx-arm64
  recipe-maintainers:
    - jpuritz
  identifiers:
    - biotools:vcflib
    - doi:10.1371/journal.pcbi.1009123
    - usegalaxy-eu:vcfsort
    - usegalaxy-eu:vcfallelicprimitives
    - usegalaxy-eu:vcfbreakcreatemulti
    - usegalaxy-eu:vcffilter2
    - usegalaxy-eu:vcfcheck
    - usegalaxy-eu:vcfcombine
    - usegalaxy-eu:vcfaddinfo
    - usegalaxy-eu:vcf2tsv
    - usegalaxy-eu:vcfleftalign
    - usegalaxy-eu:vcfhethom
    - usegalaxy-eu:vcfrandomsample
    - usegalaxy-eu:vcfbedintersect
    - usegalaxy-eu:vcfgenotypes
    - usegalaxy-eu:vcffixup
    - usegalaxy-eu:vcfgeno2haplo
    - usegalaxy-eu:vcfvcfintersect
    - usegalaxy-eu:vcfanno
    - usegalaxy-eu:vcfannotate
    - usegalaxy-eu:vcfcommonsamples
    - usegalaxy-eu:vcfflatten2
    - usegalaxy-eu:vcfdistance
    - usegalaxy-eu:vcfannotategenotypes
    - usegalaxy-eu:vcfselectsamples
