{% set name = "vcflib" %}
{% set version = "1.0.12" %}
{% set sha256 = "cb1e78d675f06ae3b22ffed7e1dea317e4c7f826e51e5b5dabd80240efbe1019" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
- url: https://github.com/vcflib/vcflib/releases/download/v{{ version }}/{{ name }}-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-CMakeLists.patch
    - tabix.patch
- url: https://ziglang.org/download/0.12.1/zig-linux-x86_64-0.12.1.tar.xz  # [linux and x86_64]
  sha256: 8860fc9725c2d9297a63008f853e9b11e3c5a2441217f99c1e3104cc6fa4a443  # [linux and x86_64]
  folder: zig-linux-x86_64-0.12.1  # [linux and x86_64]
- url: https://ziglang.org/download/0.12.1/zig-linux-aarch64-0.12.1.tar.xz  # [linux and aarch64]
  sha256: 27d4fef393e8d8b5f3b1d19f4dd43bfdb469b4ed17bbc4c2283c1b1fe650ef7f  # [linux and aarch64]
  folder: zig-linux-aarch64-0.12.1  # [linux and aarch64]
- url: https://ziglang.org/download/0.12.1/zig-macos-x86_64-0.12.1.tar.xz  # [osx and x86_64]
  sha256: 68f309c6e431d56eb42648d7fe86e8028a23464d401a467831e27c26f1a8d9c9  # [osx and x86_64]
  folder: zig-macos-x86_64-0.12.1  # [osx and x86_64]
- url: https://ziglang.org/download/0.12.1/zig-macos-aarch64-0.12.1.tar.xz  # [osx and arm64]
  sha256: 6587860dbbc070e1ee069e1a3d18ced83b7ba7a80bf67b2c57caf7c9ce5208b1  # [osx and arm64]
  folder: zig-macos-aarch64-0.12.1  # [osx and arm64]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('vcflib', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
    - pybind11-global
    # python really only used as a build tool; no ${PREFIX}/bin/python needed.
    - python >=3
    - pkg-config
  host:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - zlib
    - htslib
    - tabixpp
    - wfa2-lib
    - pandoc
  run:
    - python >=3
    - perl
    - htslib
    - tabixpp
    - wfa2-lib
    - eigen
    - jsoncpp
    - wget

test:
  requires:
    - wget
  commands:
    - "vcfwave -h"
    - "vcffirstheader < /dev/null"
    - "vcfsort < /dev/null"
    - "vcfstreamsort --help"
    - "wget -O test.vcf https://raw.githubusercontent.com/vcflib/vcflib/a610b7444daab0c9e974d9a001550bf8dd644770/test/data/regression/vcffilter_2.vcf"
    - "vcfuniq test.vcf"

about:
  home: "https://github.com/vcflib/vcflib"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Command-line tools for manipulating VCF files."
  dev_url: "https://github.com/vcflib/vcflib"
  doc_url: "https://github.com/vcflib/vcflib/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    #zig osx-arm64 error: error(link): undefined reference to symbol 'dyld_stub_binder'
    - osx-arm64
  recipe-maintainers:
    - jpuritz
  identifiers:
    - biotools:vcflib
    - doi:10.1371/journal.pcbi.1009123
    - usegalaxy-eu:vcfsort
    - usegalaxy-eu:vcfallelicprimitives
    - usegalaxy-eu:vcfbreakcreatemulti
    - usegalaxy-eu:vcffilter2
    - usegalaxy-eu:vcfcheck
    - usegalaxy-eu:vcfcombine
    - usegalaxy-eu:vcfaddinfo
    - usegalaxy-eu:vcf2tsv
    - usegalaxy-eu:vcfleftalign
    - usegalaxy-eu:vcfhethom
    - usegalaxy-eu:vcfrandomsample
    - usegalaxy-eu:vcfbedintersect
    - usegalaxy-eu:vcfgenotypes
    - usegalaxy-eu:vcffixup
    - usegalaxy-eu:vcfgeno2haplo
    - usegalaxy-eu:vcfvcfintersect
    - usegalaxy-eu:vcfanno
    - usegalaxy-eu:vcfannotate
    - usegalaxy-eu:vcfcommonsamples
    - usegalaxy-eu:vcfflatten2
    - usegalaxy-eu:vcfdistance
    - usegalaxy-eu:vcfannotategenotypes
    - usegalaxy-eu:vcfselectsamples
