{% set name = "primerForge" %}
{% set version = "1.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/dr-joe-wirth/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8d8c49186568541a6426da6042e1576c9250baeaabfbd078163325cb01feb483

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  entry_points:
    - primerForge=bin.main:main
  run_exports:
    - {{ pin_subpackage('primerforge', max_pin="x.x") }}

requirements:
  host:
    - python >=3.9,<3.12
    - pip
  run:
    - python >=3.9,<3.12
    - biopython ==1.81
    - ispcr
    - khmer >=2.1.1
    - numpy
    - primer3-py >=2.0
    - pyahocorasick
    - scipy >=1.10

test:
  commands:
    - primerForge --help
    - primerForge --check_install

about:
  home: https://github.com/dr-joe-wirth/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "primerForge: software to identify primers that can be used to distinguish genomes"

extra:
  recipe-maintainers:
    - dr-joe-wirth
