{% set name = "falco" %}
{% set version = "1.2.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/smithlabcode/falco/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f4031fa97207bed1fbc92d858a021113aa02abfa502c02fd47e2bdc7a86569c

build:
  number: 0
  run_exports:
    # falco is currently not intended to be stable between minor versions (x.x).
    - {{ pin_subpackage('falco', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
  host:
    - zlib
    - htslib
  run:
    - htslib

test:
  commands:
    - falco

about:
  home: 'https://github.com/smithlabcode/falco'
  license: 'GPL-3.0-only'
  license_family: GPL3
  license_file: LICENSE
  summary: 'falco is a drop-in C++ implementation of FastQC to assess the quality of sequence reads.'
  doc_url: 'https://falco.readthedocs.io'
  dev_url: 'https://github.com/smithlabcode/falco'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - andrewdavidsmith
    - guilhermesena1
  identifiers:
    - biotools:falco
    - usegalaxy-eu:falco
