{% set name = "blastbesties" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blastbesties-{{ version }}.tar.gz
  sha256: 5d66264863667a505309e87e33bc186d40b98ff68c96c93c0273a68a8197757c

build:
  number: 0
  noarch: python
  entry_points:
    - blastbesties = blastbesties.app:main
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('blastbesties', max_pin="x") }}

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm
  run:
    - python >=3.7

test:
  imports:
    - blastbesties
  commands:
    - blastbesties --help

about:
  home: https://github.com/Adamtaranto/blast-besties
  license: MIT
  summary: 'Rapid discovery of reciprocal best blast pairs from BLAST output files.'
  license_family: MIT
  license_file: LICENSE
