{% set name = "perl-string-diff" %}
{% set version = "0.10" %}
{% set sha256 = "4e6b44afb30c6eacec7d3398d596fb4da8ec30ff05bf1be7b1759b50f91c2840" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SC/SCHWIGON/String-Diff-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Fix tests failing because of the change in perl-yaml library
    # https://github.com/yappo/p5-String-Diff/pull/8/commits/cf34e0b93fe89fb24f91cfaf998b5b563f269eb2
    # - 0001-fix-tests.patch

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("perl-string-diff", max_pin="x.x") }}

requirements:
  build:
    - make
    - perl
    - perl-module-build-tiny
    - perl-algorithm-diff
    - perl-yaml
    - perl-test-base

  run:
    - perl
    - perl-algorithm-diff

test:
  imports:
    - String::Diff

about:
  home: https://github.com/yappo/p5-String-Diff
  license: perl_5
  summary: 'Simple diff to String'
