{% set name = "biobb_flexserv" %}
{% set version = "5.0.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90c2b03541d144026f2f6866e8fd166b0440f73a7c34c83f49b81dd826374edc

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  entry_points:
    - bd_run = biobb_flexserv.flexserv.bd_run:main
    - dmd_run = biobb_flexserv.flexserv.dmd_run:main
    - nma_run = biobb_flexserv.flexserv.nma_run:main
    - pcz_zip = biobb_flexserv.pcasuite.pcz_zip:main
    - pcz_unzip = biobb_flexserv.pcasuite.pcz_unzip:main
    - pcz_animate = biobb_flexserv.pcasuite.pcz_animate:main
    - pcz_bfactor = biobb_flexserv.pcasuite.pcz_bfactor:main
    - pcz_collectivity = biobb_flexserv.pcasuite.pcz_collectivity:main
    - pcz_evecs = biobb_flexserv.pcasuite.pcz_evecs:main
    - pcz_hinges = biobb_flexserv.pcasuite.pcz_hinges:main
    - pcz_info = biobb_flexserv.pcasuite.pcz_info:main
    - pcz_lindemann = biobb_flexserv.pcasuite.pcz_lindemann:main
    - pcz_stiffness = biobb_flexserv.pcasuite.pcz_stiffness:main
    - pcz_similarity = biobb_flexserv.pcasuite.pcz_similarity:main
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - biobb_common =={{ version }}
    - flexserv ==1.0.2
    - pcasuite ==1.0.0
    - perl

test:
  imports:
    - biobb_flexserv
    - biobb_flexserv.flexserv
    - biobb_flexserv.pcasuite

about:
  home: https://github.com/bioexcel/biobb_flexserv
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Biobb_flexserv is the BioBB module collection for biomolecular flexibility studies on protein 3D structures.
  description: "biobb_flexserv allows the generation of protein conformational ensembles from 3D structures and the analysis of its molecular flexibility. It is based on the work included in the FlexServ server (https://mmb.irbbarcelona.org/FlexServ/, Camps et. al., FlexServ: an integrated tool for the analysis of protein flexibility, Bioinformatics, Volume 25, Issue 13, 1 July 2009, Pages 1709–1710, https://doi.org/10.1093/bioinformatics/btp304).\nBiobb (BioExcel building blocks) packages are Python\
    \ building blocks that\ncreate new layer of compatibility and interoperability over popular\n
    \ bioinformatics tools.\nThe latest documentation of this package can be found in our readthedocs site: http://biobb_vs.readthedocs.io/en/latest/).\n"
