{% set name = "admixtools" %}
{% set version = "8.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DReichLab/AdmixTools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fb9347542cf847f8f6e0cf5abc62e2ff615de4a53c20fa8d0b7d9e4bc4216f12
  patches:
    - patch
    - makefile-compiler.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('admixtools', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - gsl
    - openblas
  run:
    - gsl
    - openblas

about:
  home: "https://github.com/DReichLab/AdmixTools"
  license: Free for Academic Use
  summary: 'ADMIXTOOLS (Patterson et al. 2012) is a software package that supports formal tests of whether admixture occurred, and makes it possible to infer admixture proportions and dates.'
  dev_url: "https://github.com/DReichLab/AdmixTools"
  doc_url: "https://github.com/DReichLab/AdmixTools/blob/v{{ version }}/README"

test:
  commands:
    - "qp3Pop 2>&1 | grep Usage"

extra:
  identifiers:
    - biotools:AdmixTools
    - doi:10.1534/genetics.112.145037
