{% set version = "2.3.0" %}
{% set sha256 = "e3d15d065148ed9dd25315868a31ec6c8a645d254a28ff2dcd01b23aed8b136d" %}

package:
  name: rnaalishapes
  version: 2.5.0

source:
  sha256: {{ sha256 }}
  # the repository "fold-grammars" contains sources for several programs, i.e. pKiss, RNAshapes, ...
  # thus, the version number does not correspond to the RNAalishapes version number
  url: https://github.com/jlab/fold-grammars/archive/{{ version }}.tar.gz

build:
  number: 0
  skip: False # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas
  run:
    - {{ compiler('cxx') }}
    - perl
    - bellmans-gapc >=2024.01.12
    - libopenblas

test:
  commands:
    - RNAalishapes -h
    - RNAalishapes CGCAUGCUAGUCGCG

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/rnaalishapes
  license: 'GPLv3+'
  license_file: LICENSE
  summary: "RNAalishapes is a tool for secondary structure prediction, using shape abstraction. Input is a multiple sequence alignment. Pseudoknots are not considered at all."

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btu649
