{% set version = "2.3.1" %}
{% set packagename = "knotinframe" %}
{% set sha256 = "d9ab68329e48709cffbf5ed775f905bdddebab470d70836bb522993b971d48af" %}

package:
  name: {{ packagename }}
  version: 2.2.0

source:
  sha256: {{ sha256 }}
  # the repository "fold-grammars" contains sources for several programs, i.e. pKiss, RNAshapes, ...
  # thus, the version number does not correspond to the {{ packagename }} version number
  url: https://github.com/jlab/fold-grammars/archive/{{ version }}.tar.gz

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('knotinframe', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - bellmans-gapc >=2020.12.08
  run:
    - perl
    - bellmans-gapc >=2020.12.08

test:
  commands:
  - echo "AUGC" | knotinframe | grep 'No suitable slippery sites'

about:
  home: https://bibiserv.cebitec.uni-bielefeld.de/{{ packagename }}
  license: 'GPLv3+'
  license_file: LICENSE
  summary: 'Predicts -1 frameshift sites with simple pseudoknots'

extra:
  identifiers:
    - doi:10.1093/nar/gkn578
    - doi:10.1093/bioinformatics/btu649
