{% set name = "pyprophet" %}
{% set version = "2.2.7" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a4cd5f0ba66f12d99515dfdcf318d8fc2f0c8e16202d99bf9c75c6e5ceecd2c8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  entry_points:
    - pyprophet=pyprophet.main:cli
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --no-cache-dir . -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - pypdf
    - libgomp  # [linux]  
    - llvm-openmp  # [osx]
  run:
    - python
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - {{ pin_compatible("numpy") }}
    - scipy
    - python-duckdb
    - pandas >=0.17
    - numexpr >=2.1
    - scikit-learn >=0.17
    - matplotlib-base
    - tabulate
    - pyarrow
    - xgboost
    - hyperopt
    - statsmodels >=0.8.0
    - click
    - pypdf
    - typing-extensions

test:
  imports:
    - pyprophet
  commands:
    - pyprophet --help

about:
  home: https://github.com/PyProphet/pyprophet
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "PyProphet: Semi-supervised learning and scoring of OpenSWATH results."
  dev_url: https://github.com/PyProphet/pyprophet

extra:
  additional-platforms:
    - linux-aarch64
  container:
    # Click requires the extended container
    extended-base: true
